### ISSUE TITLE
What is the exact title of your 5500XT?

### ISSUE THREAD

**Issue by telepati** [vastxie/ASUS-PRIME-Z390P_9600K_RX5500XT_UHD630#1]
Hi, I wanna buy the same graphics card. Could you please send me the page with the model of the graphics card you are using?

**Comment by vastxie** [comment]
This is from Sapphire's official website.

[PULSE RX 5500 XT 8G GDDR6](https://www.sapphiretech.com/en/consumer/pulse-radeon-rx-5500-xt-8g-gddr6)

<img width="306" alt="" src="https://user-images.githubusercontent.com/24899308/104275819-8ec9e100-54de-11eb-8447-9b2d6de696fd.png">

**Comment by telepati** [comment]
Thank you.
